{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE OverloadedStrings #-}
module Main where

import qualified AgdaStrategy        as AS
import qualified AgdaInteraction     as AI
import qualified AgdaApp             as AA

import           Control.Lens
import           Data.Monoid
import qualified Options.Applicative as OA
import           System.IO
import           Text.Printf
import Control.Monad.IO.Class

-- | Options for the app
data MartinOpt = MartinOpt
  { _onlyPrint  :: Bool
  , _splitDepth :: Int
  , _proofDepth :: Int
  , _verbose    :: Bool
  , _agdaApp    :: Bool
  , _agdaFile   :: FilePath
  }

makeLenses ''MartinOpt

-- | App options parser
progOptionParser :: OA.Parser MartinOpt
progOptionParser = MartinOpt
  <$> OA.switch
        (OA.short 'p' <>
         OA.long "print" <>
         OA.help "Print strategy and quit")
  <*> OA.option OA.auto
        (OA.metavar "SPLD" <>
         OA.short 's' <>
         OA.long "split-depth" <>
         OA.help "the maximum number of nested patterns when searching for variables to split on" <>
         OA.value 4)
  <*> OA.option OA.auto
        (OA.metavar "PRFD" <>
         OA.short 'd' <>
         OA.long "proof-depth" <>
         OA.help "the maximum depth of terms generated by the proof search" <>
         OA.value 7)
  <*> OA.switch
        (OA.short 'v' <>
         OA.long "verbose" <>
         OA.help "print verbose debug messages during execution")
  <*> OA.switch
        (OA.short 'a' <>
         OA.long "app" <>
         OA.help "run the terminal-app (highly experimental)")
  <*> OA.argument OA.str
        (OA.metavar "FILE" <>
         OA.help "Path of the Agda file containing the exercise" )

main :: IO ()
main = do
  options <- OA.execParser opts
  let file = view agdaFile options
  if view onlyPrint options
     then AS.runStrategyGenerator 0 file
     else if view agdaApp options
            then AA.runApp file
            else AI.runInteractiveSession 0 file

  where
    opts = OA.info (OA.helper <*> progOptionParser)
      ( OA.fullDesc
      <> OA.progDesc "Run the tutor on the Agda exercise in FILE"
      <> OA.header "martin - an interactive Agda tutor"
      )

